### ISSUE TITLE
How to use preview templates?

### ISSUE THREAD

**Issue by Jeroen005** [tnottu/fractal-twig-adapter#1]
Hi Tnottu,

How can I use your Twig adapter with the [Preview layouts](http://fractal.build/guide/components/preview-layouts) from Fractal?

I got these errors:
`Error parsing twig template @preview:`
`TwigException: include function does not exist and is not defined in the context`

Jeroen

**Comment by tnottu** [comment]
Heya,

There shouldn't much difference to what the Fractal guide says. Two things worth checking come to mind:
1. Have you defined a preview-layout in the Fractal config file? Like this:  
   `fractal.components.set('default.preview', '@preview');`
2. Have you created a preview-component (e.g. `components/preview.twig`) ? Like this:  

```
<html>
    <head>
        <!-- head stuff here -->
    </head>
    <body>
        {{ yield | raw }}
    </body>
</html>
```

**Comment by Jeroen005** [comment]
Thnxs! I forgot the `raw` twig filter in my template.
Issue solved ;-).
