### ISSUE TITLE
Verbose console output

### ISSUE THREAD

**Issue by delrueba** [tnottu/fractal-twig-adapter#2]
Hi Tnottu

Is there a specific reason for the console.log in the 'Custom loader for @component reference handles' ?
adapter.js, line 28

Can we remove this or add a settings option to prevent it?
I feel it really clutters up the console output during the build process.

I'm happy to make a pull request!

Bart

**Comment by tnottu** [comment]
No specific reason. It was probably there for debugging reasons. I merged your pull-request #3, thanks for the contribution!
